export const Fonts = {
  JosefinSans_Bold: 'JosefinSans-Bold',
  JosefinSans_Medium: 'JosefinSans-Medium',
  JosefinSans_Regular: 'JosefinSans-Regular',
  JosefinSans_SemiBold: 'JosefinSans-SemiBold',
  Poppins_Black: 'Poppins-Black',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Light: 'Poppins-Light',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_ThinItalic: 'Poppins-ThinItalic',

  Roboto_Black: 'Roboto-Black',
  Roboto_BlackItalic: 'Roboto-BlackItalic',
  Roboto_Bold: 'Roboto-Bold',
  Roboto_BoldItalic: 'Roboto-BoldItalic',
  Roboto_Italic: 'Roboto-Italic',
  Roboto_Light: 'Roboto-Light',
  Roboto_LightItalic: 'Roboto-LightItalic',
  Roboto_Medium: 'Roboto-Medium',
  Roboto_MediumItalic: 'Roboto-MediumItalic',
  Roboto_Regular: 'Roboto-Regular',
  Roboto_Thin: 'Roboto-Thin',
  Roboto_ThinItalic: 'Roboto-ThinItalic',
};
